### ISSUE TITLE
Is there a way to ad hoc refresh user data with changes made in directus

### ISSUE THREAD

**Issue by laportem** [becem-gharbi/nuxt-directus#48]
How does the user data get fetched from directus?

If I made some changes to the user data directly in directus
The changes are not instantly reflected in the frontend. Even if I do a hard browser refresh or call the fetchUser() or readMe() functions on app startup, login page, or at the press of a button.

However, the changes do get reflected in the frontend after some time delay.
It looks like changes to user data are fetched on a timely basis and not ad hoc at an event

**Comment by vanling** [comment]
Do you happen to have some caching enabled in your Directus .env configuration?

**Comment by laportem** [comment]
sure, I have redis enabled in my docker compose

CACHE_ENABLED: 'true'
CACHE_STORE: 'redis'
REDIS: 'redis://cache:${REDIS_PORT}'

**Comment by vanling** [comment]
You could temporary disable the caching in directus and find out if thats the culprit. Sound like a caching issue, especially because you also tried to call fetchUser/readMe directly.

**Comment by laportem** [comment]
Ok, with directus cache turned off the problem goes away.
But it does not solve my underlining issue as I need to have directus cache turned on for contents

Any ideas on how to get around it?

**Comment by vanling** [comment]
I haven't had extensive experience with caching in Directus, but I would recommend exploring [Directus's config options](https://docs.directus.io/self-hosted/config-options.html#cache), especially the CACHE_AUTO_PURGE section.

I genuinely hope this steers you in the right direction. If you still have questions, the Directus [discussions](https://github.com/directus/directus/discussions) and the Directus Discord are great places to seek further insights.

Please note that this seems unrelated to nuxt-directus, so we might consider closing this issue here. Thank you for understanding!
