### ISSUE TITLE
User get unlogged when trying to access not found page

### ISSUE THREAD

**Issue by Vincent-HD** [becem-gharbi/nuxt-directus#76]
Hi !

Thanks again for your work !

I noticed that as soon as I try to access a page that doesn't exists, the cookie get destroyed and therefor the user get disconnected.

Log in -> Cookie inserted -> type `<yoursite>/unknownpage` -> Cookie is destroyed -> Nuxt error 404 -> click on back to home -> user is now unlogged.

Another behavior with global auth:

Log in -> Cookie inserted -> type `<yoursite>/unknownpage` -> Redirect to /login page (even tho we're still supposed to be logged in) -> type user + password + submit form -> Nuxt error 404 -> Back to home -> still unlogged

![Animation](https://github.com/becem-gharbi/nuxt-directus/assets/61592570/0aa7e820-77ad-43ac-9a73-aa1487c875f8)

Is it supposed to happen ?

**Comment by BlackDahlia313** [comment]
@Vincent-HD are you using Directus 10.10?

**Comment by Vincent-HD** [comment]
> @Vincent-HD are you using Directus 10.10?

Not currently, it's actually pretty outdated, but it shouldn't affect auth right ?

**Comment by BlackDahlia313** [comment]
> > @Vincent-HD are you using Directus 10.10?
> 
> Not currently, it's actually pretty outdated, but it shouldn't affect auth right ?

10.10 introduces some breaking auth changes so I was wondering if that could have been it. 

I'm not sure of the minimum required Directus version needed for this, but I know the SDK got a significant update a few versions ago. I'll let @becem-gharbi speak on that.

edit: But I have had this issue on local host as well. Once I put everything on the same domain, cookies acted normally. 

#Directus and Nuxt apps should share the same domain name because cookies's sameSite policy is set to lax

**Comment by Vincent-HD** [comment]
> 10.10 introduces some breaking auth changes so I was wondering if that could have been it.
> 
> I'm not sure of the minimum required Directus version needed for this, but I know the SDK got a significant update a few versions ago. I'll let @becem-gharbi speak on that.
> 
> But I have had this issue on local host as well. Once I put everything on the same domain, cookies acted normally.

Yes I also had problem with cookies, like after refresh I was losing the cookie, but now it works as intended, it's been in production for two month, but I still have this problem when trying to access unknown pages so I think it's not related on cookies security policies

**Comment by Vincent-HD** [comment]
I also just noticed that when using global auth, between the logged in step (the one that's not supposed to happen), the whole page get stuck (can't even scroll) few seconds before being redirected to the Nuxt's error page

**Comment by becem-gharbi** [comment]
Hi, thanks for this issue,

The problem occurs on ssr. First nuxt runs the [auth](https://github.com/becem-gharbi/nuxt-directus/blob/main/src/runtime/plugins/auth.ts) plugin to refresh the access token when the user is logged in. This results in refresh token being [passed](https://github.com/becem-gharbi/nuxt-directus/blob/main/src/runtime/composables/useDirectusSession.ts#L68) to the ssr response via a cookie. Then when nuxt discovers that the page does not exist it throws an error and renders the error page. The problem is that the plugin re-runs and performs the refresh logic on the first refresh token sent by the original request and not on the second one on the ssr response. Thus directus rejects the refresh request as not authorized and the user is logged [out](https://github.com/becem-gharbi/nuxt-directus/blob/main/src/runtime/composables/useDirectusSession.ts#L81).

The solution can be to skip the refresh logic on server-side if an error is thrown. Or maybe to solve the issue on nuxt core.
